- hosts: all
  become: true
  tags: basic
  pre_tasks:
    - name: Set authorized key took from file
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  vars:
      swap_file_size_mb: "{{ 2048 if ansible_memtotal_mb > 2048 else ansible_memtotal_mb }}"
  roles:
    - role: stouts.hostname
    - role: geerlingguy.swap
    - role: ypsman.resolv
    - role: manala.apt
    - role: manala.motd
    - role: manala.ntp
    - role: manala.ssh
    - role: manala.sudo
    - role: manala.timezone
    - role: manala.vim
    - role: manala.fail2ban
    - role: geerlingguy.firewall
