- hosts: all
  become: true
  tags: basic
  pre_tasks:
    - name: Set authorized key took from file
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  roles:
    - { role: manala.apt }

